import type { LocalizedText } from './locale-utils'

export const guideYears: Record<string, number> = { g1: 60, g2: 7, g3: 3, g4: 42 }

export const guideCopy: Record<string, { name: string; area: LocalizedText; intro: LocalizedText }> = {
  g1: {
    name: 'Makoto Yamaguchi',
    area: { ja: '長野県・小谷村', en: 'Otari, Nagano', zh: '长野县・小谷村', es: 'Otari, Nagano', de: 'Otari, Nagano', fr: 'Otari, Nagano', it: 'Otari, Nagano' },
    intro: { ja: 'この谷で生まれ育って60年。里山の暮らしと山の恵み、ぜんぶ案内します。', en: 'Born and raised in this valley. I can show you satoyama life, mountain traditions, and the small details visitors usually miss.', zh: '在这座山谷出生长大60年。我可以带你了解里山生活、山里的传统和游客容易错过的小细节。', es: 'Nací y crecí en este valle. Te enseñaré la vida satoyama, las tradiciones de montaña y esos pequeños detalles que suelen pasar desapercibidos.', de: 'Ich bin in diesem Tal aufgewachsen. Ich zeige dir das Satoyama-Leben, Bergtraditionen und die kleinen Dinge, die Besucher oft übersehen.', fr: 'Je suis né et j’ai grandi dans cette vallée. Je vous ferai découvrir la vie satoyama, les traditions de montagne et les petits détails que l’on manque souvent.', it: 'Sono nato e cresciuto in questa valle. Ti mostrerò la vita satoyama, le tradizioni di montagna e i piccoli dettagli che spesso sfuggono ai visitatori.' },
  },
  g2: {
    name: 'Sayaka Tamura',
    area: { ja: '石川県・能登町', en: 'Noto, Ishikawa', zh: '石川县・能登町', es: 'Noto, Ishikawa', de: 'Noto, Ishikawa', fr: 'Noto, Ishikawa', it: 'Noto, Ishikawa' },
    intro: { ja: '東京から能登に来て7年。暮らし始めた頃の目線も、今の地域の目線も、どちらも大切に案内します。', en: 'I came to Noto from Tokyo seven years ago. I guide with both a newcomer’s perspective and the local understanding I have built since then.', zh: '我从东京来到能登已经7年。我会同时用刚搬来时的视角和现在积累的当地理解来为你介绍。', es: 'Llegué a Noto desde Tokio hace siete años. Guío combinando la mirada de quien llegó de fuera con el conocimiento local que he adquirido.', de: 'Ich kam vor sieben Jahren aus Tokio nach Noto. Ich verbinde die Sicht einer Neuankömmlingin mit dem lokalen Wissen, das ich seither aufgebaut habe.', fr: 'Je suis arrivée à Noto depuis Tokyo il y a sept ans. Je guide avec à la fois le regard d’une nouvelle arrivante et la compréhension locale acquise depuis.', it: 'Sono arrivata a Noto da Tokyo sette anni fa. Guido unendo lo sguardo di chi è appena arrivato alla conoscenza locale costruita nel tempo.' },
  },
  g3: {
    name: 'Yosuke Nakamura',
    area: { ja: '福岡県・八女市', en: 'Yame, Fukuoka', zh: '福冈县・八女市', es: 'Yame, Fukuoka', de: 'Yame, Fukuoka', fr: 'Yame, Fukuoka', it: 'Yame, Fukuoka' },
    intro: { ja: '福岡市の大学に通いながら、八女の茶農家で3年間フィールドワーク中。地域の外から通う目線も活かして案内します。', en: 'I study in Fukuoka City and have spent three years doing fieldwork with tea farmers in Yame. I bring the perspective of someone who keeps coming back from nearby.', zh: '我在福冈市上大学，已经连续3年到八女茶农那里做田野调查。我会用“从附近不断回来的人”的视角来介绍这里。', es: 'Estudio en Fukuoka y llevo tres años haciendo trabajo de campo con productores de té en Yame. Aporto la mirada de alguien que vuelve con frecuencia desde una zona cercana.', de: 'Ich studiere in Fukuoka und arbeite seit drei Jahren regelmäßig mit Teebauern in Yame. Dabei bringe ich die Sicht eines Menschen ein, der immer wieder aus der Umgebung kommt.', fr: 'J’étudie à Fukuoka et je mène depuis trois ans un travail de terrain avec des producteurs de thé à Yame. J’apporte le regard de quelqu’un qui revient régulièrement depuis les environs.', it: 'Studio a Fukuoka e da tre anni svolgo attività sul campo con i coltivatori di tè di Yame. Porto il punto di vista di chi torna spesso da una zona vicina.' },
  },
  g4: {
    name: 'Hisako Kobayashi',
    area: { ja: '京都府・美山町', en: 'Miyama, Kyoto', zh: '京都府・美山町', es: 'Miyama, Kioto', de: 'Miyama, Kyoto', fr: 'Miyama, Kyoto', it: 'Miyama, Kyoto' },
    intro: { ja: '美山で暮らして42年。かやぶきの里の四季、祭り、暮らしの知恵をゆっくり分かち合います。', en: 'I have lived in Miyama for 42 years. I love sharing the seasons, festivals, and everyday wisdom of the thatched-roof village.', zh: '我在美山生活了42年。很乐意慢慢分享茅草屋村落的四季、祭典和生活智慧。', es: 'Vivo en Miyama desde hace 42 años. Me encanta compartir las estaciones, los festivales y la sabiduría cotidiana del pueblo de tejados de paja.', de: 'Ich lebe seit 42 Jahren in Miyama und teile gern die Jahreszeiten, Feste und Alltagsweisheiten des Dorfes mit Reetdächern.', fr: 'Je vis à Miyama depuis 42 ans. J’aime partager les saisons, les fêtes et les savoirs du quotidien du village aux toits de chaume.', it: 'Vivo a Miyama da 42 anni. Mi piace condividere le stagioni, le feste e la saggezza quotidiana del villaggio dai tetti di paglia.' },
  },
}

export const travelerCopy: Record<string, { country: LocalizedText; status: LocalizedText; bio: LocalizedText; interests: LocalizedText[] }> = {
  t1: {
    country: { ja: 'スペイン', en: 'Spain', zh: '西班牙', es: 'España', de: 'Spanien', fr: 'Espagne', it: 'Spagna' },
    status: { ja: '能登を旅行中', en: 'Traveling in Noto', zh: '正在能登旅行', es: 'Viajando por Noto', de: 'Unterwegs in Noto', fr: 'En voyage à Noto', it: 'In viaggio a Noto' },
    bio: { ja: '観光地より、地元の市場や海辺の暮らしが好き。次は朝市を歩きたい。', en: 'I love local markets and seaside life more than famous sights. Next: the morning market.', zh: '比起著名景点，我更喜欢当地市场和海边生活。下一站想去逛早市。', es: 'Me gustan más los mercados locales y la vida junto al mar que los lugares famosos. Próxima parada: el mercado matinal.', de: 'Lokale Märkte und das Leben am Meer interessieren mich mehr als berühmte Sehenswürdigkeiten. Als Nächstes: der Morgenmarkt.', fr: 'Je préfère les marchés locaux et la vie au bord de la mer aux sites célèbres. Prochaine étape : le marché du matin.', it: 'Preferisco i mercati locali e la vita sul mare ai luoghi famosi. Prossima tappa: il mercato mattutino.' },
    interests: [{ ja: '食', en: 'Food', zh: '美食', es: 'Comida', de: 'Essen', fr: 'Cuisine', it: 'Cibo' }, { ja: '海', en: 'Sea', zh: '海', es: 'Mar', de: 'Meer', fr: 'Mer', it: 'Mare' }, { ja: '暮らし', en: 'Local life', zh: '当地生活', es: 'Vida local', de: 'Alltag', fr: 'Vie locale', it: 'Vita locale' }],
  },
  t2: {
    country: { ja: 'フランス', en: 'France', zh: '法国', es: 'Francia', de: 'Frankreich', fr: 'France', it: 'Francia' },
    status: { ja: '小谷村へ2回目の旅', en: 'Second trip to Otari', zh: '第二次来到小谷村', es: 'Segundo viaje a Otari', de: 'Zweite Reise nach Otari', fr: 'Deuxième voyage à Otari', it: 'Secondo viaggio a Otari' },
    bio: { ja: '山と小さな集落が好き。前回教わった場所を、今度は旅仲間にも共有したい。', en: 'I love mountains and small villages. I want to share the places locals showed me last time.', zh: '我喜欢山和小村庄。这次想把上次当地人带我去过的地方分享给其他旅人。', es: 'Me encantan las montañas y los pueblos pequeños. Quiero compartir con otros viajeros los lugares que me enseñaron la última vez.', de: 'Ich liebe Berge und kleine Dörfer. Die Orte, die mir Einheimische letztes Mal gezeigt haben, möchte ich diesmal mit anderen Reisenden teilen.', fr: 'J’aime la montagne et les petits villages. Cette fois, je veux partager avec d’autres voyageurs les lieux que les habitants m’ont montrés.', it: 'Amo le montagne e i piccoli villaggi. Questa volta voglio condividere con altri viaggiatori i luoghi che mi hanno mostrato gli abitanti.' },
    interests: [{ ja: '自然', en: 'Nature', zh: '自然', es: 'Naturaleza', de: 'Natur', fr: 'Nature', it: 'Natura' }, { ja: '写真', en: 'Photography', zh: '摄影', es: 'Fotografía', de: 'Fotografie', fr: 'Photographie', it: 'Fotografia' }, { ja: '里山', en: 'Satoyama', zh: '里山', es: 'Satoyama', de: 'Satoyama', fr: 'Satoyama', it: 'Satoyama' }],
  },
  t3: {
    country: { ja: '台湾', en: 'Taiwan', zh: '台湾', es: 'Taiwán', de: 'Taiwan', fr: 'Taïwan', it: 'Taiwan' },
    status: { ja: '八女のお茶文化を勉強中', en: 'Learning about Yame tea culture', zh: '正在学习八女茶文化', es: 'Aprendiendo sobre la cultura del té de Yame', de: 'Lernt die Teekultur von Yame kennen', fr: 'Découvre la culture du thé de Yame', it: 'Sta imparando la cultura del tè di Yame' },
    bio: { ja: 'お茶と工芸が好き。地元の人に教わったことを旅の記録にしています。', en: 'Tea and crafts are my thing. I keep notes on what local people teach me during my trips.', zh: '我喜欢茶和手工艺，会把旅途中从当地人那里学到的东西记录下来。', es: 'Me encantan el té y la artesanía. Anoto lo que me enseña la gente local durante mis viajes.', de: 'Ich liebe Tee und Handwerk und halte fest, was mir Menschen vor Ort auf meinen Reisen beibringen.', fr: 'J’adore le thé et l’artisanat. Je note ce que les habitants m’apprennent pendant mes voyages.', it: 'Amo il tè e l’artigianato e annoto ciò che imparo dalle persone del posto durante i viaggi.' },
    interests: [{ ja: 'お茶', en: 'Tea', zh: '茶', es: 'Té', de: 'Tee', fr: 'Thé', it: 'Tè' }, { ja: '工芸', en: 'Crafts', zh: '工艺', es: 'Artesanía', de: 'Handwerk', fr: 'Artisanat', it: 'Artigianato' }, { ja: '文化', en: 'Culture', zh: '文化', es: 'Cultura', de: 'Kultur', fr: 'Culture', it: 'Cultura' }],
  },
}

export const furusatoRecommendations: { image: string; place: LocalizedText; reason: LocalizedText; tags: LocalizedText[] }[] = [
  { image: '/events/event-1.png', place: { ja: '長野・小谷村', en: 'Otari, Nagano', zh: '长野・小谷村', es: 'Otari, Nagano', de: 'Otari, Nagano', fr: 'Otari, Nagano', it: 'Otari, Nagano' }, reason: { ja: '里山、雪国の暮らし、静かな集落。人との距離が近い。', en: 'Satoyama, snow-country life, and small villages where relationships grow naturally.', zh: '里山、雪国生活和安静村落，很容易与当地人建立联系。', es: 'Satoyama, vida en la nieve y pequeños pueblos donde las relaciones nacen de forma natural.', de: 'Satoyama, Schneeland-Alltag und kleine Dörfer, in denen Nähe ganz natürlich entsteht.', fr: 'Satoyama, vie sous la neige et petits villages où les liens se créent naturellement.', it: 'Satoyama, vita nella neve e piccoli villaggi dove i legami nascono naturalmente.' }, tags: [{ ja: '自然', en: 'Nature', zh: '自然', es: 'Naturaleza', de: 'Natur', fr: 'Nature', it: 'Natura' }, { ja: '里山', en: 'Satoyama', zh: '里山', es: 'Satoyama', de: 'Satoyama', fr: 'Satoyama', it: 'Satoyama' }] },
  { image: '/events/event-2.png', place: { ja: '石川・能登町', en: 'Noto, Ishikawa', zh: '石川・能登町', es: 'Noto, Ishikawa', de: 'Noto, Ishikawa', fr: 'Noto, Ishikawa', it: 'Noto, Ishikawa' }, reason: { ja: '朝市、海、発酵食。食卓から地域の暮らしに入っていける。', en: 'Morning markets, the sea, and fermented food — enter local life through the table.', zh: '早市、海和发酵食品，从餐桌开始认识当地生活。', es: 'Mercados matinales, mar y fermentados: entra en la vida local a través de la mesa.', de: 'Morgenmärkte, Meer und fermentierte Küche – über den Esstisch in den lokalen Alltag eintauchen.', fr: 'Marchés matinaux, mer et cuisine fermentée : entrer dans la vie locale par la table.', it: 'Mercati mattutini, mare e cibi fermentati: entra nella vita locale attraverso la tavola.' }, tags: [{ ja: '食', en: 'Food', zh: '美食', es: 'Comida', de: 'Essen', fr: 'Cuisine', it: 'Cibo' }, { ja: '海', en: 'Sea', zh: '海', es: 'Mar', de: 'Meer', fr: 'Mer', it: 'Mare' }] },
  { image: '/events/event-3.png', place: { ja: '京都・美山町', en: 'Miyama, Kyoto', zh: '京都・美山町', es: 'Miyama, Kioto', de: 'Miyama, Kyoto', fr: 'Miyama, Kyoto', it: 'Miyama, Kyoto' }, reason: { ja: 'かやぶき、季節の行事、昔ながらの暮らし。ゆっくり滞在したい地域。', en: 'Thatched roofs, seasonal customs, and old ways of living — a place worth staying longer.', zh: '茅草屋、季节活动和传统生活方式，适合慢慢停留。', es: 'Tejados de paja, costumbres estacionales y formas de vida tradicionales: un lugar para quedarse con calma.', de: 'Reetdächer, saisonale Bräuche und traditionelle Lebensweisen – ein Ort zum längeren Bleiben.', fr: 'Toits de chaume, coutumes saisonnières et modes de vie traditionnels : un lieu où prendre son temps.', it: 'Tetti di paglia, usanze stagionali e vita tradizionale: un luogo in cui fermarsi più a lungo.' }, tags: [{ ja: '文化', en: 'Culture', zh: '文化', es: 'Cultura', de: 'Kultur', fr: 'Culture', it: 'Cultura' }, { ja: '暮らし', en: 'Local life', zh: '生活', es: 'Vida local', de: 'Alltag', fr: 'Vie locale', it: 'Vita locale' }] },
]
